name: Question
description: Ask a question about this package
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Read the documentation before asking a question. You should also search your question in the other issues and on StackOverflow to see if someone else has asked the same question.
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: Check all that apply
      multiple: true
      options:
        - Android
        - iOS
        - macOS
        - Web
        - Windows
        - Linux
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Your question
      description: "Describe your question"
      placeholder: ""
    validations:
      required: false
 