name: GH-Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: master
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./example
      - name: Build Web
        run: flutter build web --release
        working-directory: ./example
      - name: Deploy
        run: |
          cd example/build/web
          git init
          git config user.name "hm21"
          git config user.email "alex.frei@waio.ch"
          git remote add secure-origin https://username:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deployed Github Pages"
          git push --force secure-origin gh-pages