name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install Package Dependencies
        run: flutter pub get

      - name: format code
        run: flutter format .

      - name: analyze code
        run: flutter analyze .

      - name: run tests
        run: flutter test

      - name: Publish
        run: dart pub publish --force
