name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.19.3'
      - run: flutter pub get
      - run: flutter pub publish --dry-run
      - run: flutter pub publish -f
